#### In this module, I will write a function that calculates row echelon form of 4*4 matrix and determines if the matrix is singluar or non-singluar.

#### Next, I generalize to n by n matrix.

In [13]:
import numpy as np

def IsSingular(A):
    B=np.array(A,dtype=np.float_)
    try:
        FixFirstRow(B)
        FixSecondRow(B)
        FixThirdRow(B)
        FixFouthRow(B)
        return False
    except MatrixIsSingular:
        return True
    
class MatrixisSingluar(Exception): pass

def FixFirstRow(A):
    if A[0,0]==0:
        A[0]=A[1]+A[0]
    if A[0,0]==0:
        A[0]=A[2]+A[0]
    if A[0,0]==0:
        A[0]=A[3]+A[0]
    if A[0,0]==0:
        raise MatrixisSingluar()
    A[0]=A[0]/A[0,0]
    return A

def FixSecondRow(A):
    A[1]=A[1]-A[1,0]*A[0]
    if A[1,1]==0:
        A[1]=A[1]+A[2]
        A[1]=A[1]+A[3]
        A[1]=A[1]-A[1,0]*A[0]
    if A[1,1]==0:
        raise MatrixisSingluar()
    A[1]=A[1]/A[1,1]
    return A

def FixThirdRow(A):
    A[2]=A[2]-A[2,0]*A[0]
    A[2]=A[2]-A[2,1]*A[1]
    if A[2,2]==0:
        A[2]=A[2]+A[3]
        A[2]=A[2]-A[2,0]*A[0]
        A[2]=A[2]-A[2,1]*A[1]
    if A[2,2]==0:
        raise MatrixisSingular()
    A[2]=A[2]/A[2,2]
    return A
def FixFouthRow(A):
    A[3]=A[3]-A[3,0]*A[0]
    A[3]=A[3]-A[3,1]*A[1]
    A[3]=A[3]-A[3,2]*A[2]
    
    if A[3,3]==0:
        raise MatrixisSingular()
    A[3]=A[3]/A[3,3]
    return A


        
                      
                      
                      
                      
                      

In [7]:
A=np.array([[1,2,3,4],[2,1,4,1],[2,4,1,2],[2,3,1,6]])
A

array([[1, 2, 3, 4],
       [2, 1, 4, 1],
       [2, 4, 1, 2],
       [2, 3, 1, 6]])

In [8]:
IsSingular(A)

False

In [9]:
FixFirstRow(A)

array([[1, 2, 3, 4],
       [2, 1, 4, 1],
       [2, 4, 1, 2],
       [2, 3, 1, 6]])

In [10]:
FixSecondRow(A)

array([[1, 2, 3, 4],
       [0, 1, 0, 2],
       [2, 4, 1, 2],
       [2, 3, 1, 6]])

In [11]:
FixThirdRow(A)

array([[1, 2, 3, 4],
       [0, 1, 0, 2],
       [0, 0, 1, 1],
       [2, 3, 1, 6]])

In [12]:
FixFouthRow(A)

array([[1, 2, 3, 4],
       [0, 1, 0, 2],
       [0, 0, 1, 1],
       [0, 0, 0, 1]])

#### Generalized to n*n matrix

In [14]:
def gisSingular(A):
    B=np.array(A,dtype=np.float_)
    n = B.shape[0]
    for j in range(n):
        for k in range(j):
            B[j] = B[j]-B[j,k]*B[k]
        if B[j,j] == 0:
            for k in range(j+1,n):
                B[j] = B[k]+B[j]
            if j != n-1:
                for l in range(j):
                    B[j]=A[j]-B[1,l]*B[l]
        if B[j,j] == 0:
            return True
        B[j] = B[j]/B[j,j]
    print(B)
    return False

In [15]:
gisSingular(A)

[[1. 2. 3. 4.]
 [0. 1. 0. 2.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]


False

In [18]:
B=np.array([[1,2,3],[2,1,4],[2,4,1]])
B

array([[1, 2, 3],
       [2, 1, 4],
       [2, 4, 1]])

In [19]:
gisSingular(B)

[[ 1.          2.          3.        ]
 [-0.          1.          0.66666667]
 [-0.         -0.          1.        ]]


False